#!/usr/bin/ruby
# == Create Site
#
# Creates a new freesite to be managed by rsite
#
# === Usage
#
# ./createsite [OPTIONS] ... SITE_DIRECTORY
#
# All arguments except SITE_DIRECTORY are optional
#
# -h, --help:
#     Display this message
#
# -n, --name:
#     The name of the freesite, used in the URL, such as SSK@.../name/, defaults to the end of SITE_DIRECTORY.
#     Stick to a-zA-Z0-9_- for characters
#
# -t, --type:
#     The type of site to insert, either USK or SSK, defaults to USK
#
# -k, --keys:
#     The keys if already generated, in the format [INSERT_KEY;REQUEST_KEY], without the SSK@ bit
#
# -v, --version:
#     The initial version of the site to insert, defaults to 1
#
# SITE_DIRECTORY is the path to the base of the site to insert, eg, ~/my_flog

require 'rsite'
require 'getoptlong'
require 'rdoc/usage'

opts = GetoptLong.new(
  ['--type', '-t', GetoptLong::REQUIRED_ARGUMENT],
  ['--name', '-n', GetoptLong::REQUIRED_ARGUMENT],
  ['--help', '-h', GetoptLong::NO_ARGUMENT],
  ['--keys', '-k', GetoptLong::REQUIRED_ARGUMENT],
  ['--version', '-v', GetoptLong::REQUIRED_ARGUMENT]
)

type = 'USK'
keys = nil
version = 1
name = nil

opts.each do |opt, value|
  case opt
  when '--type':
    unless ['USK','SSK'].include? value
      puts "Type \"#{value}\" isn't recognised, please use USK or SSK"
      exit 0
    end
    type = value
  when '--name'
    if value =~ /[^a-zA-Z0-9_-]/
      puts "Name should consist of A-Z, 0-9, _ and - only"
      exit 0
    end
    name = value
  when '--keys' # Don't check keys, I have no idea how to.
    keys = value.split(';')
  when '--version'
    version = value.to_i
  when '--help'
    RDoc::usage
    exit 0
  end
end

if ARGV.length != 1
  puts "Missing dir argument (try --help)"
  exit 0
end

dir = File.expand_path(ARGV.shift)
name ||= basename(dir)

Freenet::Site.add_site(:name=>name, :keys=>keys, :version=>version, :type=>type, :dir=>dir)